author: ayan4m1
database: false
description: Zombie survival for an entire world
generator: http://dinnerbone.com/minecraft/tools/pluginator/
main: me.ayan4m1.plugins.zombo.Zombo
name: zombo
startup: postworld
version: '0.1'
commands:
    zinfo:
        description: Shows player information and statistics
        permission: zombo.info
    zready:
        description: Indicates that you are ready to advance to the next wave
        permission: zombo.ready
    zredeem:
        description: Exchange your XP for enchantments
        permission: zombo.redeem
    zresetinv:
        description: Resets inventory to default
        permissions: zombo.resetinv
    zresetwave:
        description: Reset to first wave
        permissions: zombo.resetwave
    zwave:
        description: Displays the current wave
        permission: zombo.wave